#!/bin/sh

# -rw-rw-r-- 1 rclark clark 5 Feb 10 17:19 foo1
# lrwxrwxrwx 1 rclark clark 4 Feb 10 17:20 foo1-link -> foo1

a="foo1"
b="foo1-link"

if [ -f "$a" ]
then
	echo "$a is a regular file"
fi

if [ -h "$b" ]
then
	echo "$b is a symbolic link"
fi

if [ -f "$b" ]
then
	echo "$b tests as a regular file"
fi
if [ ! -f "$b" ]
then
	echo "$b tests as not a regular file"
else
	echo "$b check to see if it tests as not a regular file, but tests as it is a regular faile"
fi
